### ISSUE TITLE
Make Promisify work on functions that can't error

### ISSUE THREAD

**Issue by appsforartists** [cscott/prfun#1]
This is the import statement for a module I'm working on:

```javascript
var fs      = require("fs");

fs = {
  "exists":     // Can't use Promisify because fs.exists can't error
                function (path) {
                  return new Promise(
                    function (resolve) {
                      return require("fs").exists(path, resolve);
                    }
                  );
                },

  "readFile":   Promise.promisify(fs.readFile),
  "writeFile":  Promise.promisify(fs.writeFile),
  "mkdir":      Promise.promisify(fs.mkdir),
  "rmRF":       Promise.promisify(require("rimraf"))
};
```

It would be awesome if I didn't have to manually promisify `fs.exists`.  Since the current API presumes there's an error argument passed into the callback, I had to..

The ideal API would probably be something like `promisify(nodeFunction, canError, names, optThis);`, but that would be a backwards incompatible change.

Are you amenable to this patch?  If so, what's the API?

**Comment by cscott** [comment]
Also, I think this would be more compact in your use case:
```
var fs = require('fs');
fs = {
  exists:  Promise.promisify(function(path, cb) { require('fs').exists(path, cb.bind(null, null)); })
}
```

**Comment by cscott** [comment]
You might also like https://www.npmjs.com/package/pn which is a better way to promisify the standard library (all at once! automatically!).
