### ISSUE TITLE
Doesn't works if I use another name instead of Promise

### ISSUE THREAD

**Issue by xgrommx** [cscott/prfun#7]
Hello! I use Babel and prfun but it doesn't works if I use another name instead of Promise. For example

``` js
"use strict";

var _prfun = require("prfun");

const asyncFn = (() => {
    var ref = (0, _prfun.async)(function* (a, b, c) {
        const x = yield Promise.resolve(a);
        const y = yield Promise.resolve(b);
        const z = yield Promise.resolve(c);

        return x + y + z;
    });
    return function asyncFn(_x, _x2, _x3) {
        return ref.apply(this, arguments);
    };
})();

asyncFn(10, 20, 30).then(sum => console.log(`Sum = ${ sum }`));
```

but if I use `var Promise = require("prfun")` It works. I cannot to control name for this one because it automatically

**Comment by cscott** [comment]
Shouldn't the `Promise.resolve(...)` in your inner function be `_prfun.resolve(...)`?  Also, `_prfun.async` uses `this` in order to determine which `Promise` class to use; it's not clear to me but it appears that the `(0, _prfun.async)` style is deliberately designed to avoid passing `this` to the `async` method.

**Comment by xgrommx** [comment]
Take a look here https://github.com/xgrommx/async-fun/tree/master/transform-async-to-module-method/prfun

**Comment by cscott** [comment]
Although `prfun` allows invoking its methods with a subclass of `prfun.Promise`, you can't invoke its methods with a superclass or unrelated `Promise` implementation.  Internally, the implementation of `prfun` methods use other `prfun` methods, and it would impose too great a performance penalty to avoid this (in addition to breaking proper subclassing).
